language: objective-c
osx_image: xcode611

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -project yavfl.xcodeproj -scheme yavflSample-iOS test -sdk iphonesimulator | xcpretty -c
#- xcodebuild -project yavfl.xcodeproj -scheme yavflSample-OSX build | xcpretty -c
- pod lib lint --quick
