language: objective-c
osx_image: beta-xcode6.3

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -project yavfl.xcodeproj -scheme yavfl-iOS test -sdk iphonesimulator | xcpretty -c
#- xcodebuild -project yavfl.xcodeproj -scheme yavfl-OSX build | xcpretty -c
- pod lib lint --quick
